@startuml LearNteach
entity Users {
    username : varchar <PK>
    --
    email : varchar
    password : varchar
    name : varchar
}

entity Communities {
    id : int <PK>
    course : int <FK>
    --
    name : varchar
    description : varchar
    picture : varchar
    type : enum('local', 'global')
}

object Chats {
    id : int <PK>
    user : varchar <FK>
    community : int <FK>
    --
    chat : varchar
    chat_date : datetime
}

entity Instructors {
    username : varchar <PK>
    --
    document : varchar
    approved : enum('yes', 'no')
    bio : varchar
    rating : int
}

entity Courses {
    id : int <PK>
    instructor : varchar <FK>
    --
    title : varchar
    description : varchar
    rating : int
    members : int
    tags : varchar
    preview : varchar
    price : int
    created_at : datetime
    updated_at : datetime
    meet_link : varchar
    meet_time : time
    meet_day : varchar
}

object Wishlists {
    id : int <PK>
    user : varchar <FK>
    course : int <FK>
}

object Carts {
    id : int <PK>
    user : varchar <FK>
    course : int <FK>
}

entity PromotionCodes {
    id : int <PK>
    course : int <FK>
    --
    code : varchar
    discount : int
    expired : date
}

object Transactions {
    id : int <PK>
    user : varchar <FK>
    course : int <FK>
    --
    promotion_code : varchar
    course_title : varchar
    user_name : varchar
    instructor_name : varchar
    course_price : int
    price : int
    discount_percentage : int
    discount : int
    tax : int
    total : int
    transaction_date : datetime
}

object EnrolledCourses {
    id : int <PK>
    user : varchar <FK>
    course : int <FK>
}

object EnrolledContents {
    id : int <PK>
    enrolled_course : int <FK>
    content : int <FK>
    --
    completed : enum('yes', 'no')
    quiz_grade : int
    type: enum('video', 'article', 'quiz')
}

entity Contents {
    id : int <PK>
    course : int <FK>
    --
    label : varchar
    approved : enum('yes', 'no')
    type: enum('video', 'article', 'quiz')
}

entity Videos {
    id : int <PK>
    --
    file : varchar
}

entity Articles {
    id : int <PK>
    --
    body : text
}

entity Quizzes {
    id : int <PK>
    --
    answer_time : time
}

object Answers {
    id : int <PK>
    question : int <FK>
    enrolled_content : int <FK>
    --
    answer_text : varchar
    correct : enum('true', 'false')
}

entity Questions {
    id : int <PK>
    quiz : int <FK>
    --
    question_text : varchar
    answer : varchar
}

entity MultipleChoises {
    id : int <PK>
    --
    choises : varchar
}

Users }o-- Wishlists
Wishlists --o{ Courses

Users }o-- EnrolledCourses
EnrolledCourses --o{ Courses

Users }o-- Carts
Carts --o{ Courses

Users }o-- Transactions
Transactions --o{ Courses

Courses }o--|| Contents
note on link
    has
end note

Courses }o--|| PromotionCodes
note on link
    use
end note

Users -- Instructors
note on link
    ISA
end note

Instructors }o--|| Courses
note on link
    has
end note

Contents -- Videos
note on link
    ISA
end note
Contents -- Quizzes
note on link
    ISA
end note
Contents -- Articles
note on link
    ISA
end note

Quizzes }o--|| Questions
note on link
    has
end note

Questions -- MultipleChoises
note on link
    ISA
end note

Courses ||--|| Communities
note on link
    has
end note

Users }o-- Chats
Chats --o{ Communities

EnrolledContents }o-- Answers
Answers --o{ Questions

EnrolledCourses }o-- EnrolledContents
EnrolledContents --o{ Contents

@enduml